default_platform(:ios)

platform :ios do
  # desc "Description of what the lane does"
  # lane :custom_lane do
  #   # add actions here: https://docs.fastlane.tools/actions
  # end
  desc "Create .app"
  lane :build_local do
    xcodebuild(
      {
        clean: true,
        build: true,
        derivedDataPath: "build",
        workspace: "./CardForm.xcworkspace",
        output_name: "CardForm.app",
        scheme: "Example_CardForm",
        sdk: "iphonesimulator",
        xcargs: "ONLY_ACTIVE_ARCH=NO"
      }
    )
  end
end
